version: '3'

services:
  cpp:
    container_name: cpp-http
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${CPP_PORT}:80
    environment:
      - PROJECT_ROOT=/usr/local/src
    volumes:
      - ./data/:/usr/local/src/data/
